#!/bin/bash

pip install -U pip
pip install -U cython

# jupyter environment

pip install -U jupyter
ipython kernel install --user

pip install -U ipyparallel
jupyter nbextension enable ipyparallel

pip install -U jupyterlab
jupyter nbextension enable jupyterlab
jupyter serverextension enable --py jupyterlab --sys-prefix

pip install -U jupyter_contrib_nbextensions
jupyter nbextension enable jupyter_contrib_nbextensions

pip install -U jupyter_nbextensions_configurator
jupyter nbextensions_configurator enable --user
jupyter contrib nbextension install --user

pip install -U jupyterthemes
pip install jupyter-c-kernel

# utils

pip install -U cookiecutter
pip install -U pyarrow
pip install -U fastparquet
pip install -U feather-format
pip install -U h5py
pip install -U numexpr
pip install -U pylint
pip install -U nose
pip install -U happybase
pip install -U line_profiler
pip install -U numba
pip install -U networkx
pip install -U mmh3

# graphics

pip install -U matplotlib
pip install -U plotly
pip install -U seaborn
pip install -U ggplot

# geo

pip install -U pytz
pip install -U pycountry

# machine learning

pip install -U numpy
pip install -U scipy
pip install -U scikit-learn
pip install -U pandas
pip install -U xgboost
pip install -U lightgbm
pip install -U catboost
pip install -U statsmodels
pip install -U ml_metrics
pip install -U rpy2

# NLP

pip install -U fuzzywuzzy
pip install -U gensim
pip install -U spacy
pip install -U nltk
pip install -U tqdm


# hyper-parameter tuning packages
pip install -U git+https://github.com/fmfn/BayesianOptimization.git
pip install -U hyperopt
pip install -U pymongo
pip install -U scikit-optimize

# Time Series
pip install -U tsfresh

# Deep Learning
pip install -U tensorflow-gpu
pip install -U keras
pip install -U pytorch

# Api
pip install -U flask

# AWS S3 
pip install -U boto

# code beautifier/formater
pip install yapf
