#!/bin/bash

# Allow access to the packages.
chmod +x _python_packages
chmod +x _R_packages

add-apt-repository ppa:remmina-ppa-team/remmina-master
apt-get update
apt-get -y install remmina remmina-plugin-rdp

apt-get -y install r-base
apt-get -y install r-base-dev
apt-get -y install openssl-devel
apt-get -y install libcurl4-openssl-dev
apt-get -y install python-pip
apt-get -y install python-dev
apt-get -y install python3-pip
apt-get -y install python3-dev
apt-get -y install python3-tk
apt-get -y install openssh-server
apt-get -y install libssh2-1-dev
apt-get -y install libssl-dev
apt-get -y install virtualenv

dir_venvs=$HOME"/venv"
dir_venv27="$dir_venvs/python2.7"
dir_venv35="$dir_venvs/python3.5"

echo "creating venv $dir_venv"

virtualenv --python=python2.7 $dir_venv27
virtualenv --python=python3.5 $dir_venv35

source $dir_venv27"/bin/activate"
./_python_packages
deactivate

source $dir_venv35"/bin/activate"
./_python_packages
deactivate

./_R_packages
