#!/bin/bash

apt-get install r-base
apt-get install openssl-devel
apt-get install libcurl4-openssl-dev
apt-get install python-pip
apt-get install python-dev
apt-get install python3-pip
apt-get install python3-dev
apt-get install openssh-server
apt-get install libssh2-1-dev
apt-get install libssl-dev
apt-get virtualenv

dir_venvs=$HOME"/venv"
dir_venv27="$dir_venvs/python2.7"
dir_venv35="$dir_venvs/python3.5"

echo "creating venv $dir_venv"

virtualenv --python=python2.7 dir_venv27
virtualenv --python=python3.5 dir_venv35

source "$dir_venv27/bin/activate"
./_python_packages
deactivate

source "$dir_venv35/bin/activate"
./_python_packages
deactivate

./_R_packages
